### ISSUE TITLE
Peer review and testing checklist 

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-microprofile-rest-client-async#1]
Peer Review: review the guide for all of the following points. 

- [x] Check that the guide has working instruction and sample code
- [x] Check the quality of code according to the best coding practices
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide

Peer Testing: test the guide for all the points. 

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [x] Define test coverage and review with team (including guide contributor, if available)
- [x] Define detail test cases 
- [x] Consider corner cases targeting the specific guide
- [x] Consider different platform tests, ie, Mac, Windows, Linux
- [x] Consider corner cases UI tests
- [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
- [x] Consider testing the `curl` command for URL visits
- [x] Consider Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, VS.code, Eclipse, IntelliJ, Microclimate
- [x] Run Acrolink Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [x] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [x] Ensure that the automation tests are able to run with continuous daily builds

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
- Table of contents 
- Headings
- Paragraphs
- code snippets
- outputs
- links
- hotspots
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by NimG98** [comment]
Grammar Edits
======
- [ ] limit the use of “you”
  - template guidelines say don't use “you” a lot

### What you'll learn
- [ ] `“You will update a template interface that maps to the remote service that you want to call to use a CompletionStage return type making the method asynchronous.”` is too long. Could you make it 2 sentences, or add commas.
- [ ] Change lines after first sentence under **What is asynchronous programming?** to:
  - “After ordering at the register and paying for your food, you’ll usually receive an order number. While your food is being prepared, you can leave the line and wait on the side. Once your order is ready, as indicated by your number being called, you can pick up your food. Your request for food has now been fulfilled. However, in a synchronous model, you would place your order and continue waiting in line at the counter, while blocking other customers from placing their order.”
- [ ] Make this change: “Asynchronous methods ~~are methods that~~ allow you to perform a lengthy operation, such as asynchronous IO.”
- [ ] Use a different word for “slowness”
  - maybe “The network might be slow..."
- [ ] Change last sentence to:
  - “These lengthy operations can block the execution of your thread when it is in use and prevent other work from being completed."

### Changing the template interface to use asynchronous methods:
- [ ] Make this change: “First, you will replace the system client interface to ~~change it for~~ **make** the methods ~~to be~~ asynchronous.”

### Responding asynchronously to an HTTP request
- [ ] Add commas here:
  - “So instead of returning a Response type, you may return a CompletionStage<Response> type.”
  - “Similar to the synchronous approach, if we successfully get the properties from the server running at a given host name, ~~then~~ the resource will respond with an HTTP status of 200 and the body will contain the system properties.”
  - “If an exception occurs, the response will have a 404 status and a body containing an error message.”
- [ ] Reduce `A completion stage represents a unit of computation once that computation completes it can either be finished or chained with more completion stages using thenApplyAsync() to perform more computations.` into 2 sentences:
  - “A completion stage represents a unit of computation. Once that computation completes, it can either be finished or chained with more completion stages, using thenApplyAsync() to perform more computations.”
- [ ] Reword the sentence:
  - “Exceptions can be handled in a callback provided to the exceptionally() method, ~~it~~ **which** functionally behaves similar to a catch block. 

### Testing the inventory application
- [ ] Change to this sentence: “Finally, the SystemEndpointTest.java file is included for you to test the basic functionality of the system service. It can be found under the src/test/java/it/io/openliberty/guides/system directory.”
- [ ] Repeated this line twice, so delete one of them: “If a test failure occurs, then you might have introduced a bug into the code.”
  

Code Edits
======
- [ ] Git clone link on site not working
- [ ] SRVE9967W errors in messages.log
  - same issue that us new interns fixed for previous guides
  - add <scope>test<scope> to JDK dependencies in pom.xml
- [ ] “// Get properties for host” comment line in `InventoryResource.java`
  - comments in user’s view not consistent with other guides (usually don’t have comments)

**Comment by proubatsis** [comment]
>  limit the use of “you”

This is reasonably in line with the frequency it shows up in other guides.

> “// Get properties for host” comment line in InventoryResource.java

I based it on the cdi guide which does have this comment: https://openliberty.io/guides/cdi-intro.html#injecting-a-dependency

---

I also fixed the guide not showing up in the list of guides.
I made a PR with the changes (#2), please review @NimG98.

**Comment by NimG98** [comment]
Everything LGTM. Peer review checklist is complete

**Comment by evelinec** [comment]
@NimG98 can you explain how the following point was done: 

- Ensure that the automation tests are able to run with continuous daily builds

**Comment by NimG98** [comment]
Daily build automation tests run successfully.

**Comment by evelinec** [comment]
Looks good.
