### ISSUE TITLE
Peer review and testing checklist

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-microprofile-rest-client-async#7]
Peer Review: review to be done by a peer member. 

- [x] Check that the guide has working instruction and sample code
- [x] Check the quality of code according to the best coding practices
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide
- [x] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [x] Run Acrolinx Checker on draft (above 70 score approximately) => 73
- [x] Consider SEO title and description for the guides 
- [x] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [x] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
- Table of contents 
- Headings
- Paragraphs
- code snippets
- outputs
- links
- hotspots
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by evelinec** [comment]
Verified that draft guide is running CT test successfully with OpenJDK8: https://travis-ci.org/OpenLiberty/draft-guide-microprofile-rest-client-async/builds/573879253

**Comment by evelinec** [comment]
Diff on the `start` and `finish` directory. Panagiotis pointed out that the diff in the `gateway` service is intended for the initial synchronous client API. 

diff -r start/ finish/
diff -r start/gateway/src/main/java/io/openliberty/guides/gateway/JobResource.java finish/gateway/src/main/java/io/openliberty/guides/gateway/JobResource.java
41,47c41,54
<     public JobListModel getJobs() {
<         try {
<             return new JobListModel(jobClient.getJobs().getResults());
<         } catch (Exception ex) {
<             // Respond with empty list on error
<             return new JobListModel();
<         }
---
>     public CompletionStage<JobListModel> getJobs() {
>         return jobClient
>             .getJobs()
>             // tag::thenApplyAsync[]
>             .thenApplyAsync((jobs) -> {
>                 return new JobListModel(jobs.getResults());
>             })
>             // end::thenApplyAsync[]
>             // tag::exceptionally[]
>             .exceptionally((ex) -> {
>                 // Respond with empty list on error
>                 return new JobListModel();
>             });
>             // end::exceptionally[]
53c60
<     public JobResultModel getJob(@PathParam("jobId") String jobId) {
---
>     public CompletionStage<JobResultModel> getJob(@PathParam("jobId") String jobId) {
59c66
<     public JobModel createJob() {
---
>     public CompletionStage<JobModel> createJob() {
diff -r start/gateway/src/main/java/io/openliberty/guides/gateway/client/JobClient.java finish/gateway/src/main/java/io/openliberty/guides/gateway/client/JobClient.java
14a15,16
> import java.util.concurrent.CompletionStage;
> 
31a34
>     // tag::getJobs[]
34c37,38
<     public JobsModel getJobs();
---
>     public CompletionStage<JobsModel> getJobs();
>     // end::getJobs[]
35a40
>     // tag::getJob[]
39c44,45
<     public JobResultModel getJob(@PathParam("jobId") String jobId);
---
>     public CompletionStage<JobResultModel> getJob(@PathParam("jobId") String jobId);
>     // end::getJob[]
40a47
>     // tag::createJob[]
43c50,51
<     public JobModel createJob();
---
>     public CompletionStage<JobModel> createJob();
>     // end::createJob[]
Only in finish/gateway/src/test/java/it/io/openliberty/guides/gateway: JobEndpointTest.java

**Comment by evelinec** [comment]
Completed
